### PR TITLE
IR Code gen methodNameFuture

### PR DESCRIPTION
**Pull request by nomisRev**

### CODE REVIEW

**Comment by nomisRev** [comment]
This is ready for review.

**Comment by nomisRev** [comment]
This is ready for review.

**Comment by nomisRev** [comment]
Tested with a local Java project, and works as expected.

**Review by Yawolf — APPROVED** [review]

**Review by raulraja — APPROVED** [review]

**Comment by nomisRev** [comment]
@serras if you have time to review, and see anything please comment 🙏

**Pull request merged**
